import type { Metadata } from 'next'
import './globals.css'
import { relative } from 'path'


export const metadata: Metadata = {
  title: 'Dinner to Door',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='relative'>
        {children}
        </body>
    </html>
  )
}
